### ISSUE TITLE
missing indentation at begin

### ISSUE THREAD

**Issue by maverickwoo** [OCamlPro/ocp-indent#160]
This is the output of version 1.4.2 at its default config. Notice that `bar`'s body is at one less indentation than `baz`:

```
foo ~bar:begin
  fun () -> ()
end
  ~baz:begin
    fun () -> ()
  end
```

**Comment by AltGr** [comment]
this is intended: basically, when you start a multi-line parameter on the same line as the function, `ocp-indent` will try to minimise extra indentation, assuming you use this style because it's the last parameter. We could discard this feature, but it really gives a much nicer layout in many case, and the only alternative would be to look-ahead to check if there are further arguments, which is a terrible idea.

In your case, I would recommend skipping a line before `~bar`.
