### ISSUE TITLE
params indentation, align_params and max_indent 

### ISSUE THREAD

**Issue by william3** [OCamlPro/ocp-indent#198]
hello, using ocp-indent 1.5.1,
I get this indentation : 
```
(* align_params=never
   max_indent=2 *)
let _ =
  let total = foo a b c
      d e in
  let ...
```

However, I would have think that the following should happen : 
```
(* align_params=never
   max_indent=2 *)

let _ =
  let total = foo a b c
    d e in
  let ...
```

this is not a big issue however

**Comment by AltGr** [comment]
The parameter `max_indent` only affects some cases (see the doc), and those don't include function application, which always adds base_indent. We try not to over-indent, while retaining, as much as possible, "correct" indentation whatever comes next in the code. And e.g.:
```
let _ =
  let x = f
    x;
    g y
  in
  x
```
doesn't feel "correct" because `x` and `g` are at the same level. So here is the reason.
