### ISSUE TITLE
Wrong indent of match in match

### ISSUE THREAD

**Issue by mauny** [OCamlPro/ocp-indent#255]
The following code is not indented correctly:
```ocaml
match expr with
| p1 -> match v1 with
| p2 -> v2
```
instead of
```ocaml
match expr with
| p1 -> match v1 with
   | p2 -> v2
```
However, when the internal `match` is at the beginning on a line, indentation is correct. Tested with version 1.6.1.

**Comment by AltGr** [comment]
This doesn't happen with the default configuration. I believe it can be caused by the combination of `with=0` (the default), which says to not indent the switch cases, and `strict_with=always`, which says to strictly respect `with` (the default is `never`).

From the manpage:

       strict_with=<always|never|auto> (default=never)
           If `never', match bars are indented, superseding `with', whenever
           `match with' doesn't start its line. If `auto', there are
           exceptions for constructs like `begin match with'. If `always',
           `with' is always strictly respected.

           Example with `strict_with=never,with=0':
               begin match foo with
               ..| _ -> bar
               end

I would advise to set `strict_with` to `auto` if you would like to keep `with=0`

**Comment by mauny** [comment]
Indeed, an extra config file was loaded while I thought I used the default configuration. I should have better rtfm ;-).

**Comment by mauny** [comment]
Thanks!
