### ISSUE TITLE
Installation fails on Mac (and Travis CI)

### ISSUE THREAD

**Issue by szeck87** [OCamlPro/ocp-indent#256]
I cannot install it on a Mac.  I installed Homebrew and ran the following:
- brew install ocaml
- brew install opam
- opam init --auto-setup
- opam install --yes ocp-indent

At which point it fails to install topkg.  It's the same error described below with the link to the job.

It also causes our Travis CI tests to fail when trying to install topkg (which cmdliner depends on) because it cannot find topfind.  This seems to be an issue with system switches, as mentioned [here](https://github.com/ocaml/opam-repository/issues/6579).  It's a fork of atom-beautify (package for Atom editor), so there is no opam repository for me to apply a fix to. Any suggestions?  Here is the job that fails:  https://travis-ci.org/szeck87/atom-beautify/jobs/274677244

**Comment by szeck87** [comment]
@AltGr Can you please look into this or point in the right direction?  Our builds have been failing for some time now.

**Comment by AltGr** [comment]
Sorry for the lag. The issue should normally have been fixed by https://github.com/ocaml/opam-repository/pull/6592 , which makes the `ocamlfind` package install a wrapper (`$(opam var prefix)/bin/opam`) around the `ocaml` command that should make sure it is run with the proper `-I` option to get access to `$(opam var prefix)/lib/toplevel/topfind`.

Here it appears that `ocamlfind` was properly installed, so something might have been wrong with the environment. Could you check the `.env` file listed in the failure message for:
- `PATH`: the opam directory should come before wherever is the OCaml system installation (or the wrapper isn't used)
- `OCAML_TOPLEVEL_PATH`: should be set to where the `topfind` file is installed

**Comment by szeck87** [comment]
Of course it works locally after you respond :).  Let me get that log file from Travis.

**Comment by szeck87** [comment]
While I figure out how to do that, I noticed that the Linux Travis build (which succeeds) has an additional package installed:  base-ocamlbuild (https://travis-ci.org/szeck87/atom-beautify/jobs/276970959).  I know nothing about ocaml, but I see on [ocamlbuild](https://github.com/ocaml/ocamlbuild) base-ocamlbuild is listed as a conflict, not a dependency.

**Comment by AltGr** [comment]
The presence of `base-ocamlbuild` seems to indicate that Travis is using a `system` switch, i.e. one that is based on a version of OCaml installed system-wide, as opposed to one compiled within opam ([FAQ entry](http://opam.ocaml.org/doc/FAQ.html#What-is-a-quot-switch-quot)). This issue only appears with system switches, because of the multiple different search paths they involve.

**Comment by AltGr** [comment]
(`base-ocamlbuild` also depends on the version of OCaml: older releases (< 4.03) included it, so this package is used as a place-holder, while newer OCaml versions need a real `ocamlbuild` package to be installed)

**Comment by szeck87** [comment]
Waiting to hear from Travis support on how to get those files.  Meanwhile, I'm going to try using ocaml 4.04.2, it seemed to start failing when the brew formula was updated to 4.05.

**Comment by szeck87** [comment]
Something must have been cached locally, I retried and it failed.  Here are those two lines from the `.env` file.

PATH=/Users/zzzz/.opam/system/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
OCAML_TOPLEVEL_PATH=/Users/zzzz/.opam/system/lib/toplevel

**Comment by szeck87** [comment]
I did some playing around.  The step **eval `opam config env`** is being skipped, thus probably why the Travis builds are failing since the path isn't updated.  But when I tried again locally it worked, since I had closed by terminal and opened it again when you asked for the env info.  Going to put that into Travis and see if it works.

**Comment by szeck87** [comment]
OK, the builds are running now.  Maybe Ocaml 4.05 changed the way it was built out where it didn't need to do that eval?

**Comment by AltGr** [comment]
This actually looks quite similar to the failures I am getting on https://github.com/ocaml/opam/pull/3059 and other PRs (e.g. https://travis-ci.org/ocaml/opam/jobs/279454219#L6216). 4.05 only, and fails with program not found. There must be something with setenv on 4.05...

**Comment by szeck87** [comment]
Hmm, ok.  I left the `eval opam config env` in the Travis file so it would pass for now https://github.com/Glavin001/atom-beautify/commit/08556b72a6779ed0ffd02c4b595a9472c0517b53.  If that's not needed when ocaml and/or opam is updated let me know and I'll drop it.
